version: '3'

services:
  score-service:
    image: result-board_score-service
    depends_on:
      - discovery-service
  student-service:
    image: result-board_student-service
    depends_on:
      - discovery-service
  result-service:
    image: result-board_result-service
    depends_on:
      - score-service
      - student-service
  discovery-service:
    image: result-board_discovery-service
  front:
    image: result-board_front
    depends_on:
      - result-service
    ports:
      - 9000:80
    links:
      - result-service
